version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:10.11
    volumes:
      - './mariadb_data:/bitnami/mariadb'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=bn_jasperreports
      - MARIADB_DATABASE=bitnami_jasperreports
  jasperreports:
    image: docker.io/bitnami/jasperreports:8
    ports:
      - '8080:8080'
    volumes:
      - './jasperreports_data:/bitnami/jasperreports'
    depends_on:
      - mariadb
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - JASPERREPORTS_DATABASE_HOST=mariadb
      - JASPERREPORTS_DATABASE_PORT_NUMBER=3306
      - JASPERREPORTS_DATABASE_USER=bn_jasperreports
      - JASPERREPORTS_DATABASE_NAME=bitnami_jasperreports


#volumes:
#  mariadb_data:
#    driver: local
#  jasperreports_data:
#    driver: local